@baseurl = http://localhost/public
@contentype = Content-Type: application/json
@authorization = Authorization: Basic tobias123@gmail.com S25JQ3NjSkdHbDN2Q3FUcDJ5YmVzb3N5WVpIWG56RDFqWVlDdG9lVA==

tobias123@gmail.com S25JQ3NjSkdHbDN2Q3FUcDJ5YmVzb3N5WVpIWG56RDFqWVlDdG9lVA==
tobiaslkj@gmail.com ZFNrMWNieThXV2h0cEFXYTVpcHZyb0g4Vk5nTUJ0eXFVZnQ4TjJOTQ==
### Create user
POST {{baseurl}}/users HTTP/1.0
{{contentype}}

{
	"email":"tobiaslkj@gmail.com",
	"first_name":"test first name",
	"last_name":"test last name",
	"password":"password"
}

### Edit User
PUT {{baseurl}}/users HTTP/1.0
{{contentype}}
{{authorization}}

{
    "email":"tobiaslkj@gmail.com",
    "first_name":"ha",
    "last_name":"woo"
}

### Create Session
POST {{baseurl}}/sessions HTTP/1.0
{{contentype}}

{
    "email":"tobiaslkj@gmail.com",
    "password":"password"
}

### Check session
GET {{baseurl}}/sessions HTTP/1.0
{{contentype}}
{{authorization}}

### Create Campaign Manager
POST {{baseurl}}/users/campaignmanagers HTTP/1.0
{{authorization}}
{{contentype}}

{
    "UEN":"T19932220",
    "organization_name":"Tobias"
}

### Get current session campagin manager information
GET {{baseurl}}/users/campaignmanagers HTTP/1.0
{{contentype}}
{{authorization}}

### Get all items
GET {{baseurl}}/items HTTP/1.1
{{contentype}}

### Create Campaign
POST {{baseurl}}/campaigns HTTP/1.0
{{authorization}}
{{contentype}}

{
    "name": "Run For Charity",
    "start_date": "2018-11-03",
    "end_date": "2018-11-04",
    "accepted_items": [1,2,3,4],
	"start_time": "12",
	"end_time": "17",
	"description": "wtfffff",
	"collection_point": "Block ass",
	"postal_code": "750469"
}

### Create Donation
POST {{baseurl}}/donations/campaigns/1 HTTP/1.0
{{authorization}}
{{contentype}}

{
	"address_id":1,
	"pickup_date":"date",
	"pickup_time":"time",
	"items":{
		"keys":[1,2,4],
		"values":[4,4,5]
	}
}

### Get all donations based on user session
GET {{baseurl}}/donations HTTP/1.0
{{authorization}}
{{contentype}}

### Get all campaigns
GET {{baseurl}}/campaigns
{{contentype}}

{
	"max":3
}

### Create address 
POST {{baseurl}}/addresses HTTP/1.0
{{authorization}}
{{contentype}}

{
	"addresses":[
		{
			"street_name":"Block 469 AdmiraltyDrive",
			"unit":"#16-55",
			"zip":"750469"
		},
		{
			"street_name":"Bhehehee",
			"unit":"#16-25",
			"zip":"750322"
		}
		]
}

### Get Addresses
GET {{baseurl}}/addresses HTTP/1.0
{{authorization}}
{{contentype}}

### Cancel Donation
PATCH {{baseurl}}/donations/2 HTTP/1.0
{{authorization}}
{{contentype}}

### View Donation
GET {{baseurl}}/donations/1
{{authorization}}
{{contentype}}

### Get org name by uen
GET {{baseurl}}/uen HTTP/1.0
{{contentype}}

{
	"uen":"T18SS068E"
}

###  Get campaign by campaign id
GET {{baseurl}}/campaigns/1 HTTP/1.0
{{contentype}}

### Campaign maanger get donations for his campaign by id
GET {{baseurl}}/donations/campaignmanagers/campaigns/1
{{contentype}}
{{authorization}}

### Campaign manager get a donation
GET {{baseurl}}/donations/1/campaignmanagers
{{contentype}}
{{authorization}}