@baseurl = http://localhost/public
@contentype = Content-Type: application/json
@authorization = Authorization: Basic tobiaslkj@gmail.com Q1JCUDAyNkNrUUZMVVdaVWh3WVUwY3BSbXhud29STUFjRXNGUVRzOQ==

### Create user
POST {{baseurl}}/users HTTP/1.0
{{contentype}}

{
	"email":"tobiaslkj@gmail.com",
	"first_name":"test first name",
	"last_name":"test last name",
	"password":"password"
}

### Edit User
PUT {{baseurl}}/users HTTP/1.0
{{contentype}}
{{authorization}}

{
    "email":"tobiaslj@gmail.com",
    "first_name":"tobi",
    "last_name":"wan"
}

### Create Session
POST {{baseurl}}/sessions HTTP/1.0
{{contentype}}

{
    "email":"tobiaslkj@gmail.com",
    "password":"password"
}

### Check session
GET {{baseurl}}/sessions HTTP/1.0
{{contentype}}
{{authorization}}

### Create Campaign Manager
POST {{baseurl}}/users/campaignmanager HTTP/1.0
{{authorization}}
{{contentype}}

{
    "UEN":"T19932220",
    "organization_name":"Tobias"
}

### Get current session campagin manager information
GET {{baseurl}}/users/campaignmanager HTTP/1.0
{{contentype}}
{{authorization}}

### Get all items
GET {{baseurl}}/items HTTP/1.1
{{contentype}}

### Create Campaign
POST {{baseurl}}/campaigns HTTP/1.0
{{authorization}}
{{contentype}}

{
    "name": "Run For Charity",
    "start_date": "2019-08-20",
    "end_date": "2019-08-21",
    "accepted_items": [1,2,3,4]
}

### Create Donation
POST {{baseurl}}/campaigns/3/donations HTTP/1.0
{{authorization}}
{{contentype}}

{
	"items":{
		"keys":[1,2,4,5],
		"values":[4,4,5,6]
	}
}

### Get donations
GET {{baseurl}}/donations HTTP/1.0
{{authorization}}
{{contentype}}

### Get all campaigns
GET {{baseurl}}/campaigns
{{contentype}}

{
     "max":1
}

### Create address

POST {{baseurl}}/users/addresses HTTP/1.0
{{authorization}}
{{contentype}}

{
	"addresses":[
		{
			"street_name":"Block 469 AdmiraltyDrive",
			"unit":"#16-55",
			"zip":"750469"
		},
		{
			"street_name":"Bhehehee",
			"unit":"#16-25",
			"zip":"750322"
		}
		]
}